/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as EconomyBusinessRouteImport } from './routes/economy-business'
import { Route as EditorialPolicyRouteImport } from './routes/editorial-policy'
import { Route as ExplainersRouteImport } from './routes/explainers'
import { Route as GeopoliticsRouteImport } from './routes/geopolitics'
import { Route as IndiaRouteImport } from './routes/india'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WorldRouteImport } from './routes/world'
import { Route as ArticleSlugRouteImport } from './routes/article.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const EconomyBusinessRoute = EconomyBusinessRouteImport.update({
  id: '/economy-business',
  path: '/economy-business',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialPolicyRoute = EditorialPolicyRouteImport.update({
  id: '/editorial-policy',
  path: '/editorial-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplainersRoute = ExplainersRouteImport.update({
  id: '/explainers',
  path: '/explainers',
  getParentRoute: () => rootRouteImport,
} as any)
const GeopoliticsRoute = GeopoliticsRouteImport.update({
  id: '/geopolitics',
  path: '/geopolitics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndiaRoute = IndiaRouteImport.update({
  id: '/india',
  path: '/india',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldRoute = WorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/economy-business': typeof EconomyBusinessRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/explainers': typeof ExplainersRoute
  '/geopolitics': typeof GeopoliticsRoute
  '/india': typeof IndiaRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/technology': typeof TechnologyRoute
  '/terms': typeof TermsRoute
  '/world': typeof WorldRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/category/$slug': typeof CategorySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/economy-business': typeof EconomyBusinessRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/explainers': typeof ExplainersRoute
  '/geopolitics': typeof GeopoliticsRoute
  '/india': typeof IndiaRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/technology': typeof TechnologyRoute
  '/terms': typeof TermsRoute
  '/world': typeof WorldRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/category/$slug': typeof CategorySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/economy-business': typeof EconomyBusinessRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/explainers': typeof ExplainersRoute
  '/geopolitics': typeof GeopoliticsRoute
  '/india': typeof IndiaRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/technology': typeof TechnologyRoute
  '/terms': typeof TermsRoute
  '/world': typeof WorldRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/category/$slug': typeof CategorySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/disclaimer'
    | '/economy-business'
    | '/editorial-policy'
    | '/explainers'
    | '/geopolitics'
    | '/india'
    | '/privacy'
    | '/search'
    | '/technology'
    | '/terms'
    | '/world'
    | '/article/$slug'
    | '/category/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/disclaimer'
    | '/economy-business'
    | '/editorial-policy'
    | '/explainers'
    | '/geopolitics'
    | '/india'
    | '/privacy'
    | '/search'
    | '/technology'
    | '/terms'
    | '/world'
    | '/article/$slug'
    | '/category/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/disclaimer'
    | '/economy-business'
    | '/editorial-policy'
    | '/explainers'
    | '/geopolitics'
    | '/india'
    | '/privacy'
    | '/search'
    | '/technology'
    | '/terms'
    | '/world'
    | '/article/$slug'
    | '/category/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DisclaimerRoute: typeof DisclaimerRoute
  EconomyBusinessRoute: typeof EconomyBusinessRoute
  EditorialPolicyRoute: typeof EditorialPolicyRoute
  ExplainersRoute: typeof ExplainersRoute
  GeopoliticsRoute: typeof GeopoliticsRoute
  IndiaRoute: typeof IndiaRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  TechnologyRoute: typeof TechnologyRoute
  TermsRoute: typeof TermsRoute
  WorldRoute: typeof WorldRoute
  ArticleSlugRoute: typeof ArticleSlugRoute
  CategorySlugRoute: typeof CategorySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/economy-business': {
      id: '/economy-business'
      path: '/economy-business'
      fullPath: '/economy-business'
      preLoaderRoute: typeof EconomyBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial-policy': {
      id: '/editorial-policy'
      path: '/editorial-policy'
      fullPath: '/editorial-policy'
      preLoaderRoute: typeof EditorialPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explainers': {
      id: '/explainers'
      path: '/explainers'
      fullPath: '/explainers'
      preLoaderRoute: typeof ExplainersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geopolitics': {
      id: '/geopolitics'
      path: '/geopolitics'
      fullPath: '/geopolitics'
      preLoaderRoute: typeof GeopoliticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/india': {
      id: '/india'
      path: '/india'
      fullPath: '/india'
      preLoaderRoute: typeof IndiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world': {
      id: '/world'
      path: '/world'
      fullPath: '/world'
      preLoaderRoute: typeof WorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DisclaimerRoute: DisclaimerRoute,
  EconomyBusinessRoute: EconomyBusinessRoute,
  EditorialPolicyRoute: EditorialPolicyRoute,
  ExplainersRoute: ExplainersRoute,
  GeopoliticsRoute: GeopoliticsRoute,
  IndiaRoute: IndiaRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  TechnologyRoute: TechnologyRoute,
  TermsRoute: TermsRoute,
  WorldRoute: WorldRoute,
  ArticleSlugRoute: ArticleSlugRoute,
  CategorySlugRoute: CategorySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
